const String kMedium = r'''
[
  {"id":"h04","category":"history","d":2,"q":"The Berlin Wall fell in which year?","a":["1987","1989","1991","1993"],"c":1,"f":"November 9, 1989 marked the opening of the wall after 28 years."},
  {"id":"h05","category":"history","d":2,"q":"Which empire was ruled by Genghis Khan?","a":["Ottoman","Roman","Mongol","Persian"],"c":2,"f":"At its peak the Mongol Empire was the largest contiguous land empire in history."},
  {"id":"h06","category":"history","d":2,"q":"Napoleon Bonaparte was exiled to which island?","a":["Corsica","Elba","Saint Helena","Sardinia"],"c":2,"f":"He was exiled to Saint Helena in 1815 after Waterloo and died there in 1821."},
  {"id":"h08","category":"history","d":2,"q":"The Magna Carta was signed in which year?","a":["1066","1215","1348","1492"],"c":1,"f":"King John signed it at Runnymede in 1215, limiting royal power."},
  {"id":"h11","category":"history","d":2,"q":"Julius Caesar was assassinated on the Ides of which month?","a":["February","March","April","June"],"c":1,"f":"He was stabbed 23 times on March 15, 44 BC."},
  {"id":"h14","category":"history","d":2,"q":"The Cold War was primarily between the USA and which country?","a":["China","Germany","USSR","Cuba"],"c":2,"f":"The Cold War lasted from 1947 to 1991, ending with the dissolution of the USSR."},
  {"id":"s04","category":"science","d":2,"q":"What is the speed of light in a vacuum (approx)?","a":["150,000 km/s","300,000 km/s","450,000 km/s","600,000 km/s"],"c":1,"f":"299,792,458 m/s — nothing in the universe can exceed this speed."},
  {"id":"s05","category":"science","d":2,"q":"DNA stands for what?","a":["Deoxyribonucleic Acid","Diribonucleic Acid","Deoxyribose Nucleic Agent","Dense Nuclear Acid"],"c":0,"f":"Watson and Crick described the double helix structure in 1953."},
  {"id":"s06","category":"science","d":2,"q":"Which element has atomic number 1?","a":["Helium","Oxygen","Hydrogen","Carbon"],"c":2,"f":"Hydrogen is the lightest and most abundant element in the universe."},
  {"id":"s09","category":"science","d":2,"q":"What is the most abundant gas in Earth's atmosphere?","a":["Oxygen","Carbon Dioxide","Nitrogen","Argon"],"c":2,"f":"Nitrogen makes up about 78% of Earth's atmosphere."},
  {"id":"s12","category":"science","d":2,"q":"Which organ produces insulin in the human body?","a":["Liver","Kidney","Pancreas","Spleen"],"c":2,"f":"The islets of Langerhans in the pancreas produce insulin and glucagon."},
  {"id":"s15","category":"science","d":2,"q":"Which vitamin is produced when skin is exposed to sunlight?","a":["Vitamin A","Vitamin C","Vitamin D","Vitamin K"],"c":2,"f":"UVB radiation triggers Vitamin D3 synthesis in the skin."},
  {"id":"g04","category":"geography","d":2,"q":"The Amazon rainforest is primarily in which country?","a":["Colombia","Peru","Venezuela","Brazil"],"c":3,"f":"Brazil contains about 60% of the Amazon rainforest."},
  {"id":"g05","category":"geography","d":2,"q":"What is the smallest country in the world by area?","a":["Monaco","San Marino","Liechtenstein","Vatican City"],"c":3,"f":"Vatican City covers just 0.44 km² inside Rome."},
  {"id":"g06","category":"geography","d":2,"q":"Which mountain is the tallest in the world?","a":["K2","Kangchenjunga","Mount Everest","Lhotse"],"c":2,"f":"Everest stands 8,848.86 m above sea level."},
  {"id":"g09","category":"geography","d":2,"q":"Which desert is the largest in the world?","a":["Sahara","Arabian","Gobi","Antarctic"],"c":3,"f":"Antarctica is technically a polar desert at 14.2 million km²."},
  {"id":"g12","category":"geography","d":2,"q":"The Great Barrier Reef is located off the coast of which country?","a":["New Zealand","Indonesia","Australia","Philippines"],"c":2,"f":"It is the world's largest coral reef system at over 2,300 km long."},
  {"id":"a03","category":"arts","d":2,"q":"Which art movement is Salvador Dalí associated with?","a":["Cubism","Surrealism","Impressionism","Dadaism"],"c":1,"f":"Dalí joined the Surrealist movement in the late 1920s."},
  {"id":"a04","category":"arts","d":2,"q":"'The Persistence of Memory' features melting what?","a":["Clocks","Candles","Ice cream","Phones"],"c":0,"f":"Dalí said the melting watches were inspired by melting Camembert cheese."},
  {"id":"a07","category":"arts","d":2,"q":"Which opera features the aria 'Nessun Dorma'?","a":["La Traviata","Madama Butterfly","Turandot","Rigoletto"],"c":2,"f":"Turandot was Puccini's final, unfinished opera, completed by Alfano in 1926."},
  {"id":"a10","category":"arts","d":2,"q":"'Girl with a Pearl Earring' was painted by?","a":["Rembrandt","Vermeer","Rubens","Hals"],"c":1,"f":"Johannes Vermeer painted it around 1665. The subject's identity remains unknown."},
  {"id":"sp03","category":"sports","d":2,"q":"How often is the FIFA World Cup held?","a":["Every 2 years","Every 3 years","Every 4 years","Every 5 years"],"c":2,"f":"The World Cup has been held every 4 years since 1930 (except 1942 and 1946)."},
  {"id":"sp04","category":"sports","d":2,"q":"In tennis, what is the score after deuce if one player wins a point?","a":["Set point","Match point","Advantage","Game"],"c":2,"f":"The player must win two consecutive points after deuce to win the game."},
  {"id":"sp07","category":"sports","d":2,"q":"A 'hat trick' in football means scoring how many goals?","a":["2","3","4","5"],"c":1,"f":"The term originates from cricket, where a bowler who took 3 wickets received a new hat."},
  {"id":"sp10","category":"sports","d":2,"q":"In which sport would you perform a 'slam dunk'?","a":["Volleyball","Basketball","Handball","Water Polo"],"c":1,"f":"The dunk was popularised by Wilt Chamberlain in the 1960s."},
  {"id":"sp11","category":"sports","d":2,"q":"How many Grand Slam tournaments are there in tennis?","a":["2","3","4","5"],"c":2,"f":"Australian Open, French Open, Wimbledon and US Open make up the four Grand Slams."},
  {"id":"p03","category":"pop","d":2,"q":"Which TV series features dragons, the Iron Throne, and Westeros?","a":["The Witcher","Vikings","Game of Thrones","House of Cards"],"c":2,"f":"Game of Thrones aired on HBO from 2011 to 2019, based on George R.R. Martin's novels."},
  {"id":"p05","category":"pop","d":2,"q":"Which singer is known as the 'Queen of Pop'?","a":["Beyoncé","Lady Gaga","Madonna","Britney Spears"],"c":2,"f":"Madonna has sold over 300 million records worldwide, the best-selling female artist of all time."},
  {"id":"p07","category":"pop","d":2,"q":"In 'Breaking Bad', what is Walter White's alias?","a":["El Chapo","Heisenberg","Scarface","The Cook"],"c":1,"f":"The alias references Werner Heisenberg, a German physicist known for the uncertainty principle."},
  {"id":"p09","category":"pop","d":2,"q":"Who wrote the Harry Potter series?","a":["Suzanne Collins","Stephanie Meyer","J.K. Rowling","Philip Pullman"],"c":2,"f":"Rowling wrote the first book in Edinburgh cafés while a single mother on welfare."},
  {"id":"p12","category":"pop","d":2,"q":"Which TV show featured the fictional drug 'Blue Sky' methamphetamine?","a":["Narcos","Ozark","Breaking Bad","The Wire"],"c":2,"f":"Blue Sky had a fictional 99.1% purity — the blue colour was a plot device to distinguish it."},
  {"id":"t03","category":"tech","d":2,"q":"What programming language was created by Guido van Rossum?","a":["Java","Ruby","Python","Perl"],"c":2,"f":"Python was released in 1991, named after Monty Python, not the snake."},
  {"id":"t04","category":"tech","d":2,"q":"Which company developed the Android operating system?","a":["Apple","Microsoft","Google","Samsung"],"c":2,"f":"Google acquired Android Inc. in 2005 for $50 million."},
  {"id":"t07","category":"tech","d":2,"q":"Which company created the first commercially successful smartphone?","a":["Nokia","BlackBerry","Apple","Motorola"],"c":2,"f":"The iPhone was unveiled by Steve Jobs on January 9, 2007."},
  {"id":"t09","category":"tech","d":2,"q":"What does 'AI' stand for?","a":["Automated Intelligence","Artificial Intelligence","Advanced Integration","Autonomous Internet"],"c":1,"f":"The term 'Artificial Intelligence' was coined by John McCarthy in 1956."},
  {"id":"t12","category":"tech","d":2,"q":"Which company owns YouTube?","a":["Meta","Amazon","Microsoft","Google"],"c":3,"f":"Google acquired YouTube in October 2006 for $1.65 billion in stock."},
  {"id":"l03","category":"literature","d":2,"q":"In which Dickens novel does Ebenezer Scrooge appear?","a":["Oliver Twist","Great Expectations","David Copperfield","A Christmas Carol"],"c":3,"f":"A Christmas Carol was written in just 6 weeks and published in December 1843."},
  {"id":"l04","category":"literature","d":2,"q":"What is the first book of the Bible?","a":["Exodus","Psalms","Genesis","Leviticus"],"c":2,"f":"Genesis describes the creation of the world and the early history of humanity."},
  {"id":"l05","category":"literature","d":2,"q":"Who wrote 'The Great Gatsby'?","a":["Ernest Hemingway","F. Scott Fitzgerald","John Steinbeck","William Faulkner"],"c":1,"f":"Fitzgerald published The Great Gatsby in 1925. It sold poorly during his lifetime."},
  {"id":"l08","category":"literature","d":2,"q":"'To be or not to be' is a line from which Shakespeare play?","a":["Macbeth","Othello","King Lear","Hamlet"],"c":3,"f":"The soliloquy is spoken by Hamlet in Act 3, Scene 1 as he contemplates existence."},



  {"id":"m02","category":"history","d":2,"q":"In which year did the Berlin Wall fall?","a":["1987","1988","1989","1990"],"c":2,"f":"The Berlin Wall fell in 1989."},
  {"id":"m03","category":"geography","d":2,"q":"Which river is the longest in the world?","a":["Amazon","Nile","Yangtze","Mississippi"],"c":1,"f":"The Nile is commonly considered the longest."},
  {"id":"m04","category":"science","d":2,"q":"What is the chemical symbol for iron?","a":["Ir","Fe","In","I"],"c":1,"f":"Fe comes from Latin 'ferrum'."},
  {"id":"m05","category":"tech","d":2,"q":"What does HTTP stand for?","a":["HyperText Transfer Protocol","HighText Transfer Protocol","HyperTool Transfer Process","Hyperlink Text Transport Protocol"],"c":0,"f":"HTTP is used for web communication."},

  {"id":"m06","category":"history","d":2,"q":"Who was the British Prime Minister during most of WWII?","a":["Winston Churchill","Neville Chamberlain","Margaret Thatcher","Tony Blair"],"c":0,"f":"Churchill led Britain during WWII."},
  {"id":"m07","category":"science","d":2,"q":"What part of the atom has a positive charge?","a":["Electron","Neutron","Proton","Photon"],"c":2,"f":"Protons carry positive charge."},
  {"id":"m08","category":"geography","d":2,"q":"Which country has the most population?","a":["USA","India","China","Russia"],"c":1,"f":"India is currently the most populous."},
  {"id":"m09","category":"arts","d":2,"q":"Who wrote 'Romeo and Juliet'?","a":["Shakespeare","Dickens","Austen","Hemingway"],"c":0,"f":"Written by William Shakespeare."},
  {"id":"m10","category":"science","d":2,"q":"What is the speed of light approximately?","a":["300,000 km/s","150,000 km/s","1,000 km/s","3,000 km/s"],"c":0,"f":"Light travels ~300,000 km/s."},

  {"id":"m11","category":"history","d":2,"q":"Which empire used Latin as its official language?","a":["Greek","Roman","Ottoman","Persian"],"c":1,"f":"Latin was official in Roman Empire."},
  {"id":"m12","category":"geography","d":2,"q":"Which continent has the Sahara Desert?","a":["Asia","Africa","Europe","Australia"],"c":1,"f":"The Sahara is in Africa."},
  {"id":"m13","category":"science","d":2,"q":"What is photosynthesis used for?","a":["Breathing","Making food in plants","Moving water","Creating rocks"],"c":1,"f":"Plants make food using sunlight."},
  {"id":"m14","category":"tech","d":2,"q":"What is RAM used for?","a":["Long-term storage","Temporary memory","Internet speed","Screen display"],"c":1,"f":"RAM is temporary memory."},
  {"id":"m15","category":"sports","d":2,"q":"How many Grand Slam tournaments are there in tennis?","a":["2","3","4","5"],"c":2,"f":"There are 4 Grand Slams."},

  {"id":"m16","category":"science","d":2,"q":"What is the main function of red blood cells?","a":["Fight infection","Carry oxygen","Digest food","Produce hormones"],"c":1,"f":"They carry oxygen."},
  {"id":"m17","category":"history","d":2,"q":"Who was the first emperor of Rome?","a":["Julius Caesar","Augustus","Nero","Caligula"],"c":1,"f":"Augustus was first Roman emperor."},
  {"id":"m18","category":"geography","d":2,"q":"Which country is both in Europe and Asia?","a":["France","Russia","Germany","Italy"],"c":1,"f":"Russia spans Europe and Asia."},
  {"id":"m19","category":"science","d":2,"q":"What is the hardest natural substance?","a":["Gold","Diamond","Iron","Quartz"],"c":1,"f":"Diamond is the hardest."},
  {"id":"m20","category":"tech","d":2,"q":"What does 'AI' primarily refer to?","a":["App Interface","Artificial Intelligence","Auto Internet","Advanced Input"],"c":1,"f":"AI = Artificial Intelligence."},

  {"id":"m21","category":"arts","d":2,"q":"Which composer wrote many symphonies including the 9th?","a":["Mozart","Beethoven","Bach","Chopin"],"c":1,"f":"Beethoven wrote the 9th Symphony."},
  {"id":"m22","category":"science","d":2,"q":"What is the boiling point of water at sea level?","a":["90°C","100°C","110°C","120°C"],"c":1,"f":"Water boils at 100°C."},
  {"id":"m23","category":"history","d":2,"q":"Which war was fought between North and South Vietnam?","a":["WWI","WWII","Vietnam War","Korean War"],"c":2,"f":"Vietnam War lasted until 1975."},
  {"id":"m24","category":"geography","d":2,"q":"What is the capital of Canada?","a":["Toronto","Ottawa","Vancouver","Montreal"],"c":1,"f":"Ottawa is the capital."},
  {"id":"m25","category":"science","d":2,"q":"What organ controls the body?","a":["Heart","Brain","Lungs","Liver"],"c":1,"f":"The brain controls the body."},

  {"id":"m26","category":"sports","d":2,"q":"How many players are on a baseball team field?","a":["7","8","9","10"],"c":2,"f":"9 players per team on field."},
  {"id":"m27","category":"tech","d":2,"q":"Which company created Android?","a":["Apple","Google","Microsoft","Samsung"],"c":1,"f":"Android was developed by Google."},
  {"id":"m28","category":"science","d":2,"q":"What is the center of an atom called?","a":["Electron","Nucleus","Proton","Orbit"],"c":1,"f":"The nucleus is the center."},
  {"id":"m29","category":"history","d":2,"q":"Who discovered penicillin?","a":["Newton","Fleming","Edison","Darwin"],"c":1,"f":"Alexander Fleming discovered it."},





 {"id":"m31","category":"science","d":2,"q":"What is the unit of electric current?","a":["Volt","Ampere","Watt","Ohm"],"c":1,"f":"Electric current is measured in amperes."},
  {"id":"m32","category":"history","d":2,"q":"Who wrote the Communist Manifesto?","a":["Marx and Engels","Lenin","Stalin","Hitler"],"c":0,"f":"Karl Marx and Friedrich Engels."},
  {"id":"m33","category":"geography","d":2,"q":"Which country has the most islands?","a":["Sweden","Indonesia","Philippines","Norway"],"c":0,"f":"Sweden has over 200,000 islands."},
  {"id":"m34","category":"science","d":2,"q":"What is acceleration?","a":["Speed change","Distance","Weight","Temperature"],"c":0,"f":"Acceleration is change in speed."},
  {"id":"m35","category":"tech","d":2,"q":"What does URL stand for?","a":["Uniform Resource Locator","Universal Route Link","Unified Resource Line","User Reference Link"],"c":0,"f":"URL is a web address."},
  {"id":"m36","category":"science","d":2,"q":"Which organ produces insulin?","a":["Liver","Pancreas","Heart","Kidney"],"c":1,"f":"Pancreas produces insulin."},
  {"id":"m37","category":"history","d":2,"q":"Which civilization built Machu Picchu?","a":["Aztec","Inca","Maya","Roman"],"c":1,"f":"Built by the Inca civilization."},
  {"id":"m38","category":"geography","d":2,"q":"What is the capital of Egypt?","a":["Cairo","Alexandria","Giza","Luxor"],"c":0,"f":"Cairo is the capital."},
  {"id":"m39","category":"science","d":2,"q":"What is density formula?","a":["mass/volume","volume/mass","mass*volume","mass+volume"],"c":0,"f":"Density = mass divided by volume."},
  {"id":"m40","category":"sports","d":2,"q":"In which sport is a 'strike' used?","a":["Football","Baseball","Tennis","Basketball"],"c":1,"f":"Strike is used in baseball."},

  {"id":"m41","category":"tech","d":2,"q":"What does CPU do?","a":["Stores files","Processes data","Displays images","Connects WiFi"],"c":1,"f":"CPU processes data."},
  {"id":"m42","category":"science","d":2,"q":"Which planet has rings?","a":["Mars","Saturn","Venus","Mercury"],"c":1,"f":"Saturn has prominent rings."},
  {"id":"m43","category":"history","d":2,"q":"Who was the first US President?","a":["Lincoln","Washington","Jefferson","Adams"],"c":1,"f":"George Washington."},
  {"id":"m44","category":"geography","d":2,"q":"Which is the largest continent?","a":["Africa","Asia","Europe","Antarctica"],"c":1,"f":"Asia is largest."},
  {"id":"m45","category":"science","d":2,"q":"What is Newton known for?","a":["Relativity","Gravity","Electricity","Evolution"],"c":1,"f":"He described gravity."},
  {"id":"m46","category":"arts","d":2,"q":"What is a painting on wet plaster called?","a":["Mosaic","Fresco","Sketch","Portrait"],"c":1,"f":"Fresco is painting on wet plaster."},
  {"id":"m47","category":"tech","d":2,"q":"Which language is used for web structure?","a":["Python","HTML","C++","Swift"],"c":1,"f":"HTML structures web pages."},
  {"id":"m48","category":"sports","d":2,"q":"How long is a marathon?","a":["21 km","42 km","50 km","60 km"],"c":1,"f":"42.195 km."},
  {"id":"m49","category":"science","d":2,"q":"What is speed formula?","a":["distance/time","time/distance","distance*time","mass/time"],"c":0,"f":"Speed = distance ÷ time."},
  {"id":"m50","category":"history","d":2,"q":"Which country started WWII in Europe?","a":["Italy","Germany","France","UK"],"c":1,"f":"Germany invaded Poland."},

  {"id":"m51","category":"geography","d":2,"q":"Which country has Tokyo?","a":["China","Japan","South Korea","Thailand"],"c":1,"f":"Tokyo is in Japan."},
  {"id":"m52","category":"science","d":2,"q":"What is photosynthesis main output?","a":["Oxygen","Carbon","Nitrogen","Hydrogen"],"c":0,"f":"Plants produce oxygen."},
  {"id":"m53","category":"tech","d":2,"q":"What is cloud storage?","a":["Physical disk","Online storage","CPU memory","Monitor memory"],"c":1,"f":"Cloud storage is online."},
  {"id":"m54","category":"sports","d":2,"q":"Which sport uses a puck?","a":["Football","Ice hockey","Tennis","Cricket"],"c":1,"f":"Ice hockey uses a puck."},
  {"id":"m55","category":"history","d":2,"q":"Who was Cleopatra?","a":["Queen of Egypt","Roman Emperor","Greek scientist","French queen"],"c":0,"f":"Queen of Egypt."},
  {"id":"m56","category":"science","d":2,"q":"What is Earth’s core made mostly of?","a":["Iron","Water","Rock","Gas"],"c":0,"f":"Mostly iron."},
  {"id":"m57","category":"geography","d":2,"q":"Which country is Paris in?","a":["Italy","France","Spain","Germany"],"c":1,"f":"Paris is in France."},
  {"id":"m58","category":"tech","d":2,"q":"What does GPU do?","a":["Audio processing","Graphics rendering","Storage","Networking"],"c":1,"f":"GPU handles graphics."},
  {"id":"m59","category":"science","d":2,"q":"What is voltage measured in?","a":["Ampere","Volt","Watt","Newton"],"c":1,"f":"Voltage is measured in volts."},
  {"id":"m60","category":"sports","d":2,"q":"How many players in volleyball team?","a":["5","6","7","8"],"c":1,"f":"6 players per team."},

  {"id":"m61","category":"history","d":2,"q":"Which empire built pyramids?","a":["Roman","Egyptian","Greek","Persian"],"c":1,"f":"Egyptians built pyramids."},
  {"id":"m62","category":"science","d":2,"q":"What is light speed in vacuum?","a":["300,000 km/s","150,000 km/s","30,000 km/s","3,000 km/s"],"c":0,"f":"About 300,000 km/s."},
  {"id":"m63","category":"geography","d":2,"q":"Which ocean is smallest?","a":["Pacific","Atlantic","Indian","Arctic"],"c":3,"f":"Arctic is smallest."},
  {"id":"m64","category":"tech","d":2,"q":"What is RAM used for?","a":["Long storage","Temporary memory","Internet","Display"],"c":1,"f":"Temporary memory."},
  {"id":"m65","category":"science","d":2,"q":"What is an electron?","a":["Positive particle","Negative particle","Neutral rock","Gas"],"c":1,"f":"Electrons are negative."},
  {"id":"m66","category":"sports","d":2,"q":"Which sport is played at Wimbledon?","a":["Football","Tennis","Cricket","Golf"],"c":1,"f":"Wimbledon is tennis."},
  {"id":"m67","category":"history","d":2,"q":"Who invented telephone?","a":["Bell","Edison","Tesla","Newton"],"c":0,"f":"Alexander Graham Bell."},
  {"id":"m68","category":"geography","d":2,"q":"Which continent is Australia?","a":["Asia","Europe","Australia","Africa"],"c":2,"f":"Australia is a continent."},
  {"id":"m69","category":"science","d":2,"q":"What is matter?","a":["Anything with mass","Light","Sound","Energy"],"c":0,"f":"Matter has mass."},




  {"id":"m71","category":"science","d":2,"q":"What is the main gas in the air we breathe?","a":["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],"c":1,"f":"Nitrogen is most abundant."},
  {"id":"m72","category":"history","d":2,"q":"Which city was divided by a wall during the Cold War?","a":["Paris","Berlin","London","Rome"],"c":1,"f":"Berlin was divided."},
  {"id":"m73","category":"geography","d":2,"q":"Which country is known as the Land of the Rising Sun?","a":["China","Japan","Thailand","India"],"c":1,"f":"Japan is called that."},
  {"id":"m74","category":"science","d":2,"q":"What does DNA store?","a":["Energy","Genetic information","Water","Oxygen"],"c":1,"f":"DNA stores genetic info."},
  {"id":"m75","category":"tech","d":2,"q":"What is an operating system?","a":["Hardware","Software that runs computer","Internet","Screen"],"c":1,"f":"OS runs the computer."},
  {"id":"m76","category":"sports","d":2,"q":"How many players in a football team on field?","a":["9","10","11","12"],"c":2,"f":"11 players."},
  {"id":"m77","category":"history","d":2,"q":"Who built the Titanic?","a":["USA","UK","Germany","France"],"c":1,"f":"Built in the UK."},
  {"id":"m78","category":"science","d":2,"q":"What is gravity?","a":["Force pulling objects","Light energy","Sound wave","Electricity"],"c":0,"f":"Gravity pulls objects."},
  {"id":"m79","category":"geography","d":2,"q":"Which is the largest country by area?","a":["USA","China","Russia","Canada"],"c":2,"f":"Russia is largest."},
  {"id":"m80","category":"tech","d":2,"q":"What is a browser?","a":["Game","App to browse internet","Hardware","Virus"],"c":1,"f":"Used to access internet."},

  {"id":"m81","category":"science","d":2,"q":"What organ pumps blood?","a":["Brain","Heart","Lungs","Liver"],"c":1,"f":"Heart pumps blood."},
  {"id":"m82","category":"history","d":2,"q":"Who was known as the 'Iron Lady'?","a":["Angela Merkel","Margaret Thatcher","Queen Elizabeth","Cleopatra"],"c":1,"f":"Margaret Thatcher."},
  {"id":"m83","category":"geography","d":2,"q":"Which desert is in Africa?","a":["Sahara","Gobi","Mojave","Arctic"],"c":0,"f":"Sahara Desert."},
  {"id":"m84","category":"sports","d":2,"q":"Which sport uses a net and ball over it?","a":["Tennis","Basketball","Football","Boxing"],"c":0,"f":"Tennis uses net."},
  {"id":"m85","category":"science","d":2,"q":"What is an atom?","a":["Smallest unit of matter","A planet","A cell","A wave"],"c":0,"f":"Atoms are matter units."},
  {"id":"m86","category":"tech","d":2,"q":"What does software mean?","a":["Physical parts","Programs","Cables","Screens"],"c":1,"f":"Software = programs."},
  {"id":"m87","category":"history","d":2,"q":"When did WWI start?","a":["1912","1914","1916","1918"],"c":1,"f":"Started in 1914."},
  {"id":"m88","category":"geography","d":2,"q":"Which continent is Antarctica?","a":["Asia","Europe","Africa","Antarctica"],"c":3,"f":"It is a continent itself."},
  {"id":"m89","category":"science","d":2,"q":"What is sound measured in?","a":["Decibels","Meters","Liters","Grams"],"c":0,"f":"Sound = decibels."},
  {"id":"m90","category":"sports","d":2,"q":"Which sport uses a bow and arrow?","a":["Archery","Football","Tennis","Boxing"],"c":0,"f":"Archery uses bow."},

  {"id":"m91","category":"science","d":2,"q":"What do lungs do?","a":["Pump blood","Breathe air","Digest food","Store energy"],"c":1,"f":"Lungs help breathing."},
  {"id":"m92","category":"history","d":2,"q":"Which wall separated East and West Germany?","a":["Great Wall","Berlin Wall","Iron Wall","Stone Wall"],"c":1,"f":"Berlin Wall."},
  {"id":"m93","category":"geography","d":2,"q":"Which country is famous for maple syrup?","a":["USA","Canada","Mexico","Brazil"],"c":1,"f":"Canada."},
  {"id":"m94","category":"tech","d":2,"q":"What does a search engine do?","a":["Cooks food","Finds information","Drives cars","Prints books"],"c":1,"f":"Finds info online."},
  {"id":"m95","category":"science","d":2,"q":"What is energy?","a":["Ability to do work","A planet","A material","A sound"],"c":0,"f":"Energy does work."},
  {"id":"m96","category":"sports","d":2,"q":"Which sport uses clubs?","a":["Golf","Boxing","Swimming","Running"],"c":0,"f":"Golf uses clubs."},
  {"id":"m97","category":"history","d":2,"q":"Who discovered gravity?","a":["Newton","Einstein","Galileo","Tesla"],"c":0,"f":"Isaac Newton."},
  {"id":"m98","category":"geography","d":2,"q":"Which is the hottest continent?","a":["Europe","Africa","Asia","Antarctica"],"c":1,"f":"Africa is hottest."},
  {"id":"m99","category":"science","d":2,"q":"What is climate?","a":["Weather over time","A planet","A machine","A rock"],"c":0,"f":"Climate = long-term weather."},
  {"id":"m100","category":"tech","d":2,"q":"What is an app?","a":["Application program","Hardware","Cable","Virus"],"c":0,"f":"App = application."},

  {"id":"m101","category":"science","d":2,"q":"What is light made of?","a":["Photons","Atoms","Cells","Water"],"c":0,"f":"Light consists of photons."},
  {"id":"m102","category":"history","d":2,"q":"Which empire was in Britain before modern UK?","a":["Roman","Ottoman","Persian","Mongol"],"c":0,"f":"Romans occupied Britain."},
  {"id":"m103","category":"geography","d":2,"q":"Which country has the Eiffel Tower?","a":["Italy","France","Spain","Germany"],"c":1,"f":"France."},
  {"id":"m104","category":"sports","d":2,"q":"Which sport is played in NBA?","a":["Football","Basketball","Tennis","Cricket"],"c":1,"f":"NBA = basketball."},
  {"id":"m105","category":"science","d":2,"q":"What is temperature measured in?","a":["Kilograms","Celsius","Liters","Meters"],"c":1,"f":"Celsius commonly."},
  {"id":"m106","category":"tech","d":2,"q":"What is a file?","a":["Stored data","A cable","A screen","A virus"],"c":0,"f":"File stores data."},
  {"id":"m107","category":"history","d":2,"q":"Which country was ancient Rome in?","a":["Italy","Greece","Egypt","France"],"c":0,"f":"Italy."},
  {"id":"m108","category":"geography","d":2,"q":"Which ocean is near USA east coast?","a":["Pacific","Atlantic","Indian","Arctic"],"c":1,"f":"Atlantic Ocean."},
  {"id":"m109","category":"science","d":2,"q":"What is evaporation?","a":["Liquid to gas","Gas to liquid","Solid to gas","Gas to solid"],"c":0,"f":"Liquid becomes gas."},

 





{"id":"m111","category":"science","d":2,"q":"What is the smallest unit of life?","a":["Atom","Cell","Molecule","Organ"],"c":1,"f":"The cell is the smallest unit of life."},
  {"id":"m112","category":"history","d":2,"q":"Which civilization built the Colosseum?","a":["Greek","Roman","Egyptian","Persian"],"c":1,"f":"Romans built the Colosseum."},
  {"id":"m113","category":"geography","d":2,"q":"Which country is famous for kangaroos?","a":["India","Australia","Canada","Brazil"],"c":1,"f":"Australia."},
  {"id":"m114","category":"tech","d":2,"q":"What does WiFi stand for?","a":["Wireless Fidelity","Wide File","Web Function","Wireless File"],"c":0,"f":"WiFi = Wireless Fidelity (commonly used term)."},
  {"id":"m115","category":"science","d":2,"q":"What is inertia?","a":["Resistance to motion change","Gravity","Heat","Light"],"c":0,"f":"Inertia is resistance to change in motion."},
  {"id":"m116","category":"sports","d":2,"q":"Which sport uses a shuttlecock?","a":["Tennis","Badminton","Cricket","Golf"],"c":1,"f":"Badminton uses shuttlecock."},
  {"id":"m117","category":"history","d":2,"q":"Who was the first man in space?","a":["Neil Armstrong","Yuri Gagarin","Buzz Aldrin","John Glenn"],"c":1,"f":"Yuri Gagarin."},
  {"id":"m118","category":"geography","d":2,"q":"Which is the longest river in Africa?","a":["Amazon","Nile","Congo","Niger"],"c":1,"f":"The Nile River."},
  {"id":"m119","category":"science","d":2,"q":"What is the main gas in stars?","a":["Oxygen","Hydrogen","Nitrogen","Helium"],"c":1,"f":"Stars are mostly hydrogen."},
  {"id":"m120","category":"tech","d":2,"q":"What is coding?","a":["Writing instructions for computers","Drawing","Cooking","Driving"],"c":0,"f":"Coding is writing instructions."},

  {"id":"m121","category":"science","d":2,"q":"What is the function of the skeleton?","a":["Produce blood","Support body","Pump air","Digest food"],"c":1,"f":"Skeleton supports body."},
  {"id":"m122","category":"history","d":2,"q":"Which war ended in 1918?","a":["WWI","WWII","Cold War","Vietnam War"],"c":0,"f":"World War I."},
  {"id":"m123","category":"geography","d":2,"q":"Which country is located in South America?","a":["Spain","Brazil","France","Germany"],"c":1,"f":"Brazil."},
  {"id":"m124","category":"sports","d":2,"q":"Which sport is known as 'the king of sports'?","a":["Basketball","Football (soccer)","Tennis","Cricket"],"c":1,"f":"Football (soccer)."},
  {"id":"m125","category":"science","d":2,"q":"What is boiling?","a":["Liquid to gas","Gas to liquid","Solid to gas","Gas to solid"],"c":0,"f":"Boiling turns liquid into gas."},
  {"id":"m126","category":"tech","d":2,"q":"What does browser do?","a":["Runs games","Opens websites","Cooks food","Stores water"],"c":1,"f":"Browsers open websites."},
  {"id":"m127","category":"history","d":2,"q":"Who was Albert Einstein?","a":["Painter","Scientist","King","Pilot"],"c":1,"f":"He was a physicist."},
  {"id":"m128","category":"geography","d":2,"q":"Which country is Tokyo in?","a":["China","Japan","Thailand","Korea"],"c":1,"f":"Japan."},
  {"id":"m129","category":"science","d":2,"q":"What is friction?","a":["Force resisting motion","Light","Sound","Heat"],"c":0,"f":"Friction slows movement."},
  {"id":"m130","category":"sports","d":2,"q":"How many periods in basketball game (NBA)?","a":["2","3","4","5"],"c":2,"f":"4 quarters."},

  {"id":"m131","category":"science","d":2,"q":"What is a planet?","a":["Star","Object orbiting a star","Moon","Comet"],"c":1,"f":"Planets orbit stars."},
  {"id":"m132","category":"history","d":2,"q":"Which ancient land is pyramids in?","a":["Greece","Egypt","Italy","India"],"c":1,"f":"Egypt."},
  {"id":"m133","category":"geography","d":2,"q":"Which continent is Europe in?","a":["North America","Europe","Africa","Asia"],"c":1,"f":"Europe."},
  {"id":"m134","category":"tech","d":2,"q":"What is hardware?","a":["Physical parts of computer","Software","Internet","App"],"c":0,"f":"Hardware is physical parts."},
  {"id":"m135","category":"science","d":2,"q":"What is sound produced by?","a":["Vibration","Light","Electricity","Gravity"],"c":0,"f":"Sound comes from vibration."},
  {"id":"m136","category":"sports","d":2,"q":"Which sport uses lanes in water?","a":["Football","Swimming","Tennis","Boxing"],"c":1,"f":"Swimming."},
  {"id":"m137","category":"history","d":2,"q":"Who discovered America in 1492?","a":["Columbus","Newton","Tesla","Edison"],"c":0,"f":"Christopher Columbus."},
  {"id":"m138","category":"geography","d":2,"q":"Which ocean is largest?","a":["Atlantic","Pacific","Indian","Arctic"],"c":1,"f":"Pacific Ocean."},
  {"id":"m139","category":"science","d":2,"q":"What is evaporation caused by?","a":["Cold","Heat","Pressure only","Gravity"],"c":1,"f":"Heat causes evaporation."},
  {"id":"m140","category":"tech","d":2,"q":"What is a virus in computing?","a":["Helpful program","Malicious software","Browser","Hardware"],"c":1,"f":"Malicious software."},

  {"id":"m141","category":"science","d":2,"q":"What do kidneys do?","a":["Pump blood","Filter waste","Make oxygen","Control vision"],"c":1,"f":"They filter waste."},
  {"id":"m142","category":"history","d":2,"q":"Which wall separated Berlin?","a":["Great Wall","Berlin Wall","Iron Wall","Stone Wall"],"c":1,"f":"Berlin Wall."},
  {"id":"m143","category":"geography","d":2,"q":"Which country has London?","a":["France","UK","Germany","Spain"],"c":1,"f":"United Kingdom."},
  {"id":"m144","category":"sports","d":2,"q":"Which sport uses pins?","a":["Bowling","Football","Tennis","Swimming"],"c":0,"f":"Bowling uses pins."},
  {"id":"m145","category":"science","d":2,"q":"What is electricity?","a":["Energy flow","Water","Rock","Gas"],"c":0,"f":"Electricity is energy flow."},
  {"id":"m146","category":"tech","d":2,"q":"What is an algorithm?","a":["Cooking recipe for computers","Virus","Cable","Screen"],"c":0,"f":"Step-by-step instructions."},
  {"id":"m147","category":"history","d":2,"q":"Who was Cleopatra?","a":["Egyptian queen","Roman soldier","Greek scientist","French queen"],"c":0,"f":"Queen of Egypt."},
  {"id":"m148","category":"geography","d":2,"q":"Which country is Berlin in?","a":["France","Germany","Italy","Spain"],"c":1,"f":"Germany."},
  {"id":"m149","category":"science","d":2,"q":"What is oxygen needed for?","a":["Breathing","Cooking","Driving","Painting"],"c":0,"f":"Breathing."},



 {"id":"m151","category":"science","d":2,"q":"What is the main function of the brain?","a":["Pump blood","Control body","Digest food","Store oxygen"],"c":1,"f":"The brain controls the body."},
  {"id":"m152","category":"history","d":2,"q":"Which empire built the pyramids?","a":["Roman","Egyptian","Greek","Persian"],"c":1,"f":"Egyptian civilization built pyramids."},
  {"id":"m153","category":"geography","d":2,"q":"Which continent is the Sahara Desert in?","a":["Asia","Africa","Europe","Australia"],"c":1,"f":"Sahara is in Africa."},
  {"id":"m154","category":"tech","d":2,"q":"What does a computer monitor do?","a":["Stores files","Displays output","Cooks food","Processes data"],"c":1,"f":"It displays output."},
  {"id":"m155","category":"science","d":2,"q":"What is a chemical reaction?","a":["Change of substances","Movement of planets","Sound wave","Light reflection"],"c":0,"f":"Substances change into new ones."},
  {"id":"m156","category":"sports","d":2,"q":"Which sport uses a bat and wicket?","a":["Cricket","Football","Tennis","Boxing"],"c":0,"f":"Cricket uses wicket."},
  {"id":"m157","category":"history","d":2,"q":"Who was Napoleon Bonaparte?","a":["French leader","British king","Scientist","Explorer"],"c":0,"f":"French military leader."},
  {"id":"m158","category":"geography","d":2,"q":"Which is the capital of USA?","a":["New York","Washington D.C.","Los Angeles","Chicago"],"c":1,"f":"Washington D.C."},
  {"id":"m159","category":"science","d":2,"q":"What is photosynthesis used for?","a":["Movement","Food production in plants","Breathing","Heating"],"c":1,"f":"Plants make food."},
  {"id":"m160","category":"tech","d":2,"q":"What does RAM stand for?","a":["Random Access Memory","Read Access Module","Run Active Memory","Rapid App Machine"],"c":0,"f":"Random Access Memory."},

  {"id":"m161","category":"science","d":2,"q":"What is gravity measured in?","a":["Newton","Volt","Ampere","Liter"],"c":0,"f":"Force is measured in Newtons."},
  {"id":"m162","category":"history","d":2,"q":"Which war involved the USA and Vietnam?","a":["WWI","WWII","Vietnam War","Cold War"],"c":2,"f":"Vietnam War."},
  {"id":"m163","category":"geography","d":2,"q":"Which ocean is near India?","a":["Atlantic","Pacific","Indian","Arctic"],"c":2,"f":"Indian Ocean."},
  {"id":"m164","category":"sports","d":2,"q":"How many holes in golf course round?","a":["9","12","18","20"],"c":2,"f":"18 holes."},
  {"id":"m165","category":"science","d":2,"q":"What is matter?","a":["Anything with mass","Light","Sound","Energy"],"c":0,"f":"Matter has mass."},
  {"id":"m166","category":"tech","d":2,"q":"What is a database?","a":["Game","Data storage system","Virus","Screen"],"c":1,"f":"Stores structured data."},
  {"id":"m167","category":"history","d":2,"q":"Who was Julius Caesar?","a":["Roman leader","King of France","Scientist","Pilot"],"c":0,"f":"Roman leader."},
  {"id":"m168","category":"geography","d":2,"q":"Which country is known for pizza?","a":["France","Italy","Spain","Germany"],"c":1,"f":"Italy."},
  {"id":"m169","category":"science","d":2,"q":"What is the main source of energy on Earth?","a":["Moon","Sun","Wind","Ocean"],"c":1,"f":"Sun."},
  {"id":"m170","category":"sports","d":2,"q":"Which sport uses a net and ball (volley)?","a":["Basketball","Volleyball","Football","Tennis"],"c":1,"f":"Volleyball."},

  {"id":"m171","category":"science","d":2,"q":"What is an ecosystem?","a":["Group of computers","Living and non-living environment","Type of animal","Chemical element"],"c":1,"f":"Interaction of living & non-living."},
  {"id":"m172","category":"history","d":2,"q":"Which city was ancient Rome in?","a":["France","Italy","Greece","Egypt"],"c":1,"f":"Italy."},
  {"id":"m173","category":"geography","d":2,"q":"Which continent is Russia mostly in?","a":["Asia","Europe","Africa","America"],"c":0,"f":"Mostly Asia."},
  {"id":"m174","category":"tech","d":2,"q":"What is coding used for?","a":["Cooking","Creating software","Driving","Painting"],"c":1,"f":"Creating software."},
  {"id":"m175","category":"science","d":2,"q":"What is evaporation?","a":["Solid to gas","Liquid to gas","Gas to liquid","Gas to solid"],"c":1,"f":"Liquid becomes gas."},
  {"id":"m176","category":"sports","d":2,"q":"Which sport uses gloves and ring?","a":["Boxing","Tennis","Football","Cricket"],"c":0,"f":"Boxing."},
  {"id":"m177","category":"history","d":2,"q":"Which empire used Latin?","a":["Roman","Ottoman","Persian","Mongol"],"c":0,"f":"Roman Empire."},
  {"id":"m178","category":"geography","d":2,"q":"Which country is Paris in?","a":["Italy","France","Spain","Germany"],"c":1,"f":"France."},
  {"id":"m179","category":"science","d":2,"q":"What is speed?","a":["Distance/time","Time/distance","Mass/time","Force/time"],"c":0,"f":"Speed = distance ÷ time."},
  {"id":"m180","category":"tech","d":2,"q":"What is internet?","a":["Global network","App","Game","Device"],"c":0,"f":"Global network."},

  {"id":"m181","category":"science","d":2,"q":"What is DNA?","a":["Protein","Genetic code","Cell wall","Gas"],"c":1,"f":"DNA carries genetic info."},
  {"id":"m182","category":"history","d":2,"q":"When did WWI end?","a":["1914","1916","1918","1920"],"c":2,"f":"1918."},
  {"id":"m183","category":"geography","d":2,"q":"Which country has Tokyo?","a":["China","Japan","Korea","Thailand"],"c":1,"f":"Japan."},
  {"id":"m184","category":"sports","d":2,"q":"Which sport uses racket and shuttle?","a":["Tennis","Badminton","Cricket","Golf"],"c":1,"f":"Badminton."},
  {"id":"m185","category":"science","d":2,"q":"What is energy?","a":["Ability to do work","Matter","Light only","Gas"],"c":0,"f":"Ability to do work."},
  {"id":"m186","category":"tech","d":2,"q":"What is an app?","a":["Software program","Hardware","Cable","Screen"],"c":0,"f":"Software program."},
  {"id":"m187","category":"history","d":2,"q":"Who discovered gravity?","a":["Newton","Einstein","Galileo","Tesla"],"c":0,"f":"Newton."},
  {"id":"m188","category":"geography","d":2,"q":"Which ocean is largest?","a":["Atlantic","Pacific","Indian","Arctic"],"c":1,"f":"Pacific."},
  {"id":"m189","category":"science","d":2,"q":"What is friction?","a":["Force resisting motion","Energy","Gas","Light"],"c":0,"f":"Resists motion."},



{"id":"m191","category":"science","d":2,"q":"What is the main function of lungs?","a":["Pump blood","Breathe air","Digest food","Store energy"],"c":1,"f":"Lungs are used for breathing."},
  {"id":"m192","category":"history","d":2,"q":"Which city was the center of the Roman Empire?","a":["Athens","Rome","Paris","Cairo"],"c":1,"f":"Rome was the capital."},
  {"id":"m193","category":"geography","d":2,"q":"Which continent is Egypt in?","a":["Asia","Africa","Europe","Australia"],"c":1,"f":"Egypt is in Africa."},
  {"id":"m194","category":"tech","d":2,"q":"What does a keyboard do?","a":["Displays images","Types text input","Stores files","Plays sound"],"c":1,"f":"Used for typing."},
  {"id":"m195","category":"science","d":2,"q":"What is the human skeleton made of?","a":["Iron","Bones","Muscles","Water"],"c":1,"f":"Skeleton is made of bones."},
  {"id":"m196","category":"sports","d":2,"q":"Which sport uses a net and ball over it?","a":["Football","Volleyball","Boxing","Running"],"c":1,"f":"Volleyball uses net."},
  {"id":"m197","category":"history","d":2,"q":"Who was the first man on the Moon?","a":["Yuri Gagarin","Neil Armstrong","Buzz Aldrin","Michael Collins"],"c":1,"f":"Neil Armstrong."},
  {"id":"m198","category":"geography","d":2,"q":"Which country is Berlin in?","a":["France","Germany","Italy","Spain"],"c":1,"f":"Berlin is in Germany."},
  {"id":"m199","category":"science","d":2,"q":"What is boiling?","a":["Liquid to gas","Gas to liquid","Solid to gas","Gas to solid"],"c":0,"f":"Liquid turns into gas."},
  {"id":"m200","category":"tech","d":2,"q":"What is software?","a":["Physical parts","Programs","Wires","Screen"],"c":1,"f":"Software = programs."},

  {"id":"m201","category":"science","d":2,"q":"What is the center of Earth called?","a":["Crust","Core","Mantle","Surface"],"c":1,"f":"Earth's core."},
  {"id":"m202","category":"history","d":2,"q":"Which war was between North and South Korea?","a":["WWI","WWII","Korean War","Vietnam War"],"c":2,"f":"Korean War."},
  {"id":"m203","category":"geography","d":2,"q":"Which ocean is between Africa and America?","a":["Pacific","Atlantic","Indian","Arctic"],"c":1,"f":"Atlantic Ocean."},
  {"id":"m204","category":"sports","d":2,"q":"How many players in volleyball team?","a":["5","6","7","8"],"c":1,"f":"6 players."},
  {"id":"m205","category":"science","d":2,"q":"What is sound?","a":["Vibration","Light","Gas","Rock"],"c":0,"f":"Sound is vibration."},
  {"id":"m206","category":"tech","d":2,"q":"What is internet used for?","a":["Cooking","Communication","Sleeping","Driving"],"c":1,"f":"Communication."},
  {"id":"m207","category":"history","d":2,"q":"Who was Cleopatra?","a":["Egyptian queen","Roman emperor","Greek scientist","French queen"],"c":0,"f":"Queen of Egypt."},
  {"id":"m208","category":"geography","d":2,"q":"Which continent is Australia in?","a":["Asia","Europe","Australia","Africa"],"c":2,"f":"Australia is a continent."},
  {"id":"m209","category":"science","d":2,"q":"What is gravity?","a":["Force pulling objects","Light","Heat","Sound"],"c":0,"f":"Pulling force."},
  {"id":"m210","category":"sports","d":2,"q":"Which sport uses a bat and ball?","a":["Cricket","Swimming","Running","Boxing"],"c":0,"f":"Cricket."},

  {"id":"m211","category":"science","d":2,"q":"What is an atom?","a":["Smallest unit of matter","Planet","Star","Wave"],"c":0,"f":"Atoms are basic units."},
  {"id":"m212","category":"history","d":2,"q":"Which empire used Latin?","a":["Roman","Greek","Egyptian","Persian"],"c":0,"f":"Roman Empire."},
  {"id":"m213","category":"geography","d":2,"q":"Which country is Italy in?","a":["Asia","Europe","Africa","America"],"c":1,"f":"Europe."},
  {"id":"m214","category":"tech","d":2,"q":"What is CPU?","a":["Computer brain","Screen","Cable","Virus"],"c":0,"f":"Processes data."},
  {"id":"m215","category":"science","d":2,"q":"What is water formula?","a":["H2O","CO2","O2","NaCl"],"c":0,"f":"H2O."},
  {"id":"m216","category":"sports","d":2,"q":"Which sport uses gloves and ring?","a":["Boxing","Tennis","Football","Golf"],"c":0,"f":"Boxing."},
  {"id":"m217","category":"history","d":2,"q":"When did WWII end?","a":["1943","1944","1945","1946"],"c":2,"f":"1945."},
  {"id":"m218","category":"geography","d":2,"q":"Which country has pyramids?","a":["Egypt","France","USA","China"],"c":0,"f":"Egypt."},
  {"id":"m219","category":"science","d":2,"q":"What is energy?","a":["Ability to do work","Matter","Light","Gas"],"c":0,"f":"Work ability."},
  {"id":"m220","category":"tech","d":2,"q":"What is a browser?","a":["App to access internet","Game","Hardware","Virus"],"c":0,"f":"Internet app."},

  {"id":"m221","category":"science","d":2,"q":"What is photosynthesis?","a":["Making food in plants","Breathing","Moving","Sleeping"],"c":0,"f":"Plants make food."},
  {"id":"m222","category":"history","d":2,"q":"Who discovered America?","a":["Columbus","Newton","Einstein","Tesla"],"c":0,"f":"Christopher Columbus."},
  {"id":"m223","category":"geography","d":2,"q":"Which continent is USA in?","a":["Asia","Europe","North America","Africa"],"c":2,"f":"North America."},
  {"id":"m224","category":"sports","d":2,"q":"Which sport uses net and racket?","a":["Tennis","Football","Boxing","Running"],"c":0,"f":"Tennis."},
  {"id":"m225","category":"science","d":2,"q":"What is temperature?","a":["Heat level","Weight","Speed","Time"],"c":0,"f":"Heat level."},
  {"id":"m226","category":"tech","d":2,"q":"What is RAM?","a":["Temporary memory","Hard drive","Screen","Cable"],"c":0,"f":"Temporary memory."},
  {"id":"m227","category":"history","d":2,"q":"Who was Napoleon?","a":["French leader","English king","German scientist","Greek soldier"],"c":0,"f":"French leader."},
  {"id":"m228","category":"geography","d":2,"q":"Which ocean is largest?","a":["Atlantic","Pacific","Indian","Arctic"],"c":1,"f":"Pacific."},
  {"id":"m229","category":"science","d":2,"q":"What is friction?","a":["Force resisting motion","Light","Gas","Water"],"c":0,"f":"Opposes motion."},



  {"id":"l10","category":"literature","d":2,"q":"Who wrote 'Crime and Punishment'?","a":["Leo Tolstoy","Ivan Turgenev","Fyodor Dostoevsky","Anton Chekhov"],"c":2,"f":"Dostoevsky wrote it in 1866 while deeply in debt, publishing it in serial form."}
]
''';
